### ISSUE TITLE
Broken link in https://github.com/LBT-CNRS/UnityMol-Releases/blob/master/LICENSE.md

### ISSUE THREAD

**Issue by RubenGarcia** [LBT-CNRS/UnityMol-Releases#5]
The document links to
https://github.com/LBT-CNRS/UnityMol-Releases/blob/master/Assets/Resources/Logo/LogoUnityMol1.0_outline.png
which does not exist.

**Comment by bam93** [comment]
That looks to me like its an issue with LFS. You need to properly checkout the project onto your local drive, then the relative link "Assets/Resources/Logo/LogoUnityMol1.0_outline.png" will work from where LICENSE.md is. It could also be related to a bandwidth limitation that we are currently experiencing, it seems there were so many attempts to download the project in a short time that the available bandwidth was exceeded and github blocked all further downloads until the quota renews the next month. We are working on a resolution for this.

**Comment by RubenGarcia** [comment]
You closed the issue, but the problem persists.

**Comment by bam93** [comment]
Sorry, maybe I misunderstood the problem. So following up on my previous reply, please confirm that:
- when you **clone the repository** (including the git-lfs part) the file "Assets/Resources/Logo/LogoUnityMol1.0_outline.png" is missing in your **local copy**. Is that the case? Because for me it is not.
- if that file exists, in your local copy, the link from the LICENSE.md file is _not_ broken

Please confirm.

**The link is not supposed nor designed to work online from the github.com website in any case,** which is what I suspected your initial message was about. Sorry should I have misinterpreted it.

We possibly may change things so that the link may also work from the github.com website, but it is not considered as an actual problem.

**Comment by HubLot** [comment]
Hi,

The broken link in the README on the master (https://github.com/LBT-CNRS/UnityMol-Releases/blob/master/Assets/Resources/Logo/LogoUnityMol1.0_outline.png) should be resolved once the branch 1.0.36 and fix_1.0.36 will be merged (you can check on the [fix_1.0.36](https://github.com/LBT-CNRS/UnityMol-Releases/tree/fix_1.0.36) that the image is correctly displayed).

**Comment by RubenGarcia** [comment]
All good then. My message was specifically about reading the documentation directly on github.com.
